// Present Continuous > Affirmative exercises registry
// Auto-generated by tooling: centralizes exercises per room.
import { PC_ROOMS_PER_SECTION, PC_SECTIONS } from "../pc-core/config.js";

const PC_AFFIRMATIVE_ROOM_2_GLOSSARY_ITEMS = [
  { tts: "like", word: "like", meaning: "a plăcea" },
  { tts: "go", word: "go", meaning: "a merge" },
  { tts: "read", word: "read", meaning: "a citi" },
  { tts: "stop", word: "stop", meaning: "a opri" },
  { tts: "watch", word: "watch", meaning: "a se uita / a privi" },
  { tts: "want", word: "want", meaning: "a vrea" },
  { tts: "wear", word: "wear", meaning: "a purta" },
  { tts: "pupils", word: "pupils", meaning: "elevi" },
  { tts: "traffic lights", word: "traffic lights", meaning: "semafor" },
  { tts: "blouse", word: "blouse", meaning: "bluză" },
];

export const PC_AFFIRMATIVE_EXERCISES_BY_ROOM = {
  //
  // Optional mini-dictionaries per room (aligned with Present Simple style).
  //

  // Room 1 – Verb -> -ing forms (20 verbs)
  1: [
    {
      id: "pc-r1-ex1",
      prompt: "run →",
      correct: "running",
      tts: "run, running",
    },
    {
      id: "pc-r1-ex2",
      prompt: "swim →",
      correct: "swimming",
      tts: "swim, swimming",
    },
    {
      id: "pc-r1-ex3",
      prompt: "stop →",
      correct: "stopping",
      tts: "stop, stopping",
    },
    {
      id: "pc-r1-ex4",
      prompt: "plan →",
      correct: "planning",
      tts: "plan, planning",
    },
    {
      id: "pc-r1-ex5",
      prompt: "shop →",
      correct: "shopping",
      tts: "shop, shopping",
    },
    {
      id: "pc-r1-ex6",
      prompt: "get →",
      correct: "getting",
      tts: "get, getting",
    },
    {
      id: "pc-r1-ex7",
      prompt: "sit →",
      correct: "sitting",
      tts: "sit, sitting",
    },
    {
      id: "pc-r1-ex8",
      prompt: "begin →",
      correct: "beginning",
      tts: "begin, beginning",
    },
    {
      id: "pc-r1-ex9",
      prompt: "travel →",
      correct: "travelling",
      tts: "travel, travelling",
    },
    {
      id: "pc-r1-ex10",
      prompt: "study →",
      correct: "studying",
      tts: "study, studying",
    },
    {
      id: "pc-r1-ex11",
      prompt: "make →",
      correct: "making",
      tts: "make, making",
    },
    {
      id: "pc-r1-ex12",
      prompt: "take →",
      correct: "taking",
      tts: "take, taking",
    },
    {
      id: "pc-r1-ex13",
      prompt: "write →",
      correct: "writing",
      tts: "write,writing",
    },
    {
      id: "pc-r1-ex14",
      prompt: "drive →",
      correct: "driving",
      tts: "drive, driving",
    },
    {
      id: "pc-r1-ex15",
      prompt: "come →",
      correct: "coming",
      tts: "come, coming",
    },
    {
      id: "pc-r1-ex16",
      prompt: "dance →",
      correct: "dancing",
      tts: "dance, dancing",
    },
    {
      id: "pc-r1-ex17",
      prompt: "read →",
      correct: "reading",
      tts: "read, reading",
    },
    {
      id: "pc-r1-ex18",
      prompt: "play →",
      correct: "playing",
      tts: "play, playing",
    },
    {
      id: "pc-r1-ex19",
      prompt: "talk →",
      correct: "talking",
      tts: "talk, talking",
    },
    {
      id: "pc-r1-ex20",
      prompt: "open →",
      correct: "opening",
      tts: "open, opening",
    },
  ],

  // Room 2 – Completează cu forma corectă a lui "to be"
  2: [
    {
      id: "pc-r2-ex1",
      template: "I [gap] doing my homework now.",
      correct: "am",
      tts: "I am doing my homework now.",
    },
    {
      id: "pc-r2-ex2",
      template: "She [gap] talking on the phone at the moment.",
      correct: "is",
      tts: "She is talking on the phone at the moment.",
    },
    {
      id: "pc-r2-ex3",
      template: "They [gap] playing football in the park.",
      correct: "are",
      tts: "They are playing football in the park.",
    },
    {
      id: "pc-r2-ex4",
      template: "We [gap] watching a film right now.",
      correct: "are",
      tts: "We are watching a film right now.",
    },
    {
      id: "pc-r2-ex5",
      template: "He [gap] listening to music in his room.",
      correct: "is",
      tts: "He is listening to music in his room.",
    },
    {
      id: "pc-r2-ex6",
      template: "You [gap] reading a very interesting book.",
      correct: "are",
      tts: "You are reading a very interesting book.",
    },
    {
      id: "pc-r2-ex7",
      template: "My sister [gap] cooking dinner in the kitchen.",
      correct: "is",
      tts: "My sister is cooking dinner in the kitchen.",
    },
    {
      id: "pc-r2-ex8",
      template: "The children [gap] drawing pictures in class.",
      correct: "are",
      tts: "The children are drawing pictures in class.",
    },
    {
      id: "pc-r2-ex9",
      template: "I [gap] learning English this week.",
      correct: "am",
      tts: "I am learning English this week.",
    },
    {
      id: "pc-r2-ex10",
      template: "My parents [gap] working late today.",
      correct: "are",
      tts: "My parents are working late today.",
    },
  ],

  // Room 3 – MCQ (choose the correct option)
  3: [
    {
      id: "pc-r3-ex1",
      prompt: "Look! The dog ___ in the garden.",
      correct: "is-running",
      tts: "Look! The dog is running in the garden.",
      options: [
        { value: "runs", label: "runs" },
        { value: "is-running", label: "is running" },
        { value: "run", label: "run" },
      ],
    },
    {
      id: "pc-r3-ex2",
      prompt: "They ___ their bikes to school today.",
      correct: "are-riding",
      tts: "They are riding their bikes to school today.",
      options: [
        { value: "are-riding", label: "are riding" },
        { value: "ride", label: "ride" },
        { value: "is-riding", label: "is riding" },
      ],
    },
    {
      id: "pc-r3-ex3",
      prompt: "I ___ for my English test now.",
      correct: "am-studying",
      tts: "I am studying for my English test now.",
      options: [
        { value: "study", label: "study" },
        { value: "am-studying", label: "am studying" },
        { value: "am-study", label: "am study" },
      ],
    },
    {
      id: "pc-r3-ex4",
      prompt: "She ___ her hair at the moment.",
      correct: "is-washing",
      tts: "She is washing her hair at the moment.",
      options: [
        { value: "washes", label: "washes" },
        { value: "is-wash", label: "is wash" },
        { value: "is-washing", label: "is washing" },
      ],
    },
    {
      id: "pc-r3-ex5",
      prompt: "We ___ breakfast in the kitchen right now.",
      correct: "are-having",
      tts: "We are having breakfast in the kitchen right now.",
      options: [
        { value: "are-having", label: "are having" },
        { value: "have", label: "have" },
        { value: "is-having", label: "is having" },
      ],
    },
    {
      id: "pc-r3-ex6",
      prompt: "My brother ___ a new video game.",
      correct: "is-playing",
      tts: "My brother is playing a new video game.",
      options: [
        { value: "plays", label: "plays" },
        { value: "is-playing", label: "is playing" },
        { value: "are-playing", label: "are playing" },
      ],
    },
    {
      id: "pc-r3-ex7",
      prompt: "The teacher ___ to the students.",
      correct: "is-talking",
      tts: "The teacher is talking to the students.",
      options: [
        { value: "is-talking", label: "is talking" },
        { value: "talks", label: "talks" },
        { value: "are-talking", label: "are talking" },
      ],
    },
    {
      id: "pc-r3-ex8",
      prompt: "You ___ too fast!",
      correct: "are-driving",
      tts: "You are driving too fast!",
      options: [
        { value: "drive", label: "drive" },
        { value: "are-driving", label: "are driving" },
        { value: "is-driving", label: "is driving" },
      ],
    },
    {
      id: "pc-r3-ex9",
      prompt: "The boys ___ basketball in the yard.",
      correct: "are-playing",
      tts: "The boys are playing basketball in the yard.",
      options: [
        { value: "are-playing", label: "are playing" },
        { value: "is-playing", label: "is playing" },
        { value: "play", label: "play" },
      ],
    },
    {
      id: "pc-r3-ex10",
      prompt: "It ___ heavily today.",
      correct: "is-raining",
      tts: "It is raining heavily today.",
      options: [
        { value: "is-raining", label: "is raining" },
        { value: "rains", label: "rains" },
        { value: "are-raining", label: "are raining" },
      ],
    },
  ],

  // Room 4 – Transformă din Present Simple în Present Continuous
  4: [
    {
      id: "pc-r4-ex1",
      template: "I eat lunch every day. → I [gap] lunch now.",
      correct: "am eating",
      tts: "I am eating lunch now.",
    },
    {
      id: "pc-r4-ex2",
      template:
        "She plays the piano every evening. → She [gap] the piano at the moment.",
      correct: "is playing",
      tts: "She is playing the piano at the moment.",
    },
    {
      id: "pc-r4-ex3",
      template: "They watch TV on weekends. → They [gap] TV right now.",
      correct: "are watching",
      tts: "They are watching TV right now.",
    },
    {
      id: "pc-r4-ex4",
      template:
        "We read a book together every now and then. → We [gap] a book together now.",
      correct: "are reading",
      tts: "We are reading a book together now.",
    },
    {
      id: "pc-r4-ex5",
      template:
        "My brother does his homework in the afternoon. → My brother [gap] his homework at the moment.",
      correct: "is doing",
      tts: "My brother is doing his homework at the moment.",
    },
    {
      id: "pc-r4-ex6",
      template:
        "The children draw pictures at the weekend. → The children [gap] pictures now.",
      correct: "are drawing",
      tts: "The children are drawing pictures now.",
    },
    {
      id: "pc-r4-ex7",
      template:
        "You write an email every week. → You [gap] an email right now.",
      correct: "are writing",
      tts: "You are writing an email right now.",
    },
    {
      id: "pc-r4-ex8",
      template:
        "He cleans his room every Saturday. → He [gap] his room at the moment.",
      correct: "is cleaning",
      tts: "He is cleaning his room at the moment.",
    },
    {
      id: "pc-r4-ex9",
      template:
        "My parents cook dinner every evening. → My parents [gap] dinner now.",
      correct: "are cooking",
      tts: "My parents are cooking dinner now.",
    },
    {
      id: "pc-r4-ex10",
      template:
        "The students listen to the teacher every day. → The students [gap] to the teacher right now.",
      correct: "are listening",
      tts: "The students are listening to the teacher right now.",
    },
  ],

  // Room 5 – Correct the mistake
  5: [
    {
      id: "pc-r5-ex1",
      template: "She is play tennis now. → She [gap] tennis now.",
      correct: "is playing",
      tts: "She is playing tennis now.",
    },
    {
      id: "pc-r5-ex2",
      template: "They are watches a film. → They [gap] a film.",
      correct: "are watching",
      tts: "They are watching a film.",
    },
    {
      id: "pc-r5-ex3",
      template: "I am study for the test. → I [gap] for the test.",
      correct: "am studying",
      tts: "I am studying for the test.",
    },
    {
      id: "pc-r5-ex4",
      template:
        "We is having breakfast at the moment. → We [gap] breakfast at the moment.",
      correct: "are having",
      tts: "We are having breakfast at the moment.",
    },
    {
      id: "pc-r5-ex5",
      template: "My dad are driving to work now. → My dad [gap] to work now.",
      correct: "is driving",
      tts: "My dad is driving to work now.",
    },
    {
      id: "pc-r5-ex6",
      template:
        "The children is drawing pictures. → The children [gap] pictures.",
      correct: "are drawing",
      tts: "The children are drawing pictures.",
    },
    {
      id: "pc-r5-ex7",
      template:
        "You are listen to music too loudly. → You [gap] to music too loudly.",
      correct: "are listening",
      tts: "You are listening to music too loudly.",
    },
    {
      id: "pc-r5-ex8",
      template: "Emma am talking to her friend. → Emma [gap] to her friend.",
      correct: "is talking",
      tts: "Emma is talking to her friend.",
    },
    {
      id: "pc-r5-ex9",
      template: "It are raining today. → It [gap] today.",
      correct: "is raining",
      tts: "It is raining today.",
    },
    {
      id: "pc-r5-ex10",
      template: "We are not play football now. → We [gap] football now.",
      correct: "are not playing",
      tts: "We are not playing football now.",
    },
  ],

  // Room 6 – Put the words in the correct order
  6: [
    {
      id: "pc-r6-ex1",
      prompt: "(now / is / reading / Anna / a book)",
      correct: "anna is reading a book now",
      tts: "Anna is reading a book now.",
    },
    {
      id: "pc-r6-ex2",
      prompt: "(are / playing / they / in the park / football)",
      correct: "they are playing football in the park",
      tts: "They are playing football in the park.",
    },
    {
      id: "pc-r6-ex3",
      prompt: "(I / for the test / am / studying / today)",
      correct: "i am studying for the test today",
      tts: "I am studying for the test today.",
    },
    {
      id: "pc-r6-ex4",
      prompt: "(is / cooking / my mum / dinner / at the moment)",
      correct: "my mum is cooking dinner at the moment",
      tts: "My mum is cooking dinner at the moment.",
    },
    {
      id: "pc-r6-ex5",
      prompt: "(are / the students / doing / their homework / now)",
      correct: "the students are doing their homework now",
      tts: "The students are doing their homework now.",
    },
    {
      id: "pc-r6-ex6",
      prompt: "(listening / we / are / to music / right now)",
      correct: "we are listening to music right now",
      tts: "We are listening to music right now.",
    },
    {
      id: "pc-r6-ex7",
      prompt: "(fixing / is / the car / my uncle / today)",
      correct: "my uncle is fixing the car today",
      tts: "My uncle is fixing the car today.",
    },
    {
      id: "pc-r6-ex8",
      prompt: "(are / the children / watching / a cartoon / now)",
      correct: "the children are watching a cartoon now",
      tts: "The children are watching a cartoon now.",
    },
    {
      id: "pc-r6-ex9",
      prompt: "(writing / is / an email / she / at the moment)",
      correct: "she is writing an email at the moment",
      tts: "She is writing an email at the moment.",
    },
    {
      id: "pc-r6-ex10",
      prompt: "(running / in the garden / the dog / is / now)",
      correct: "the dog is running in the garden now",
      tts: "The dog is running in the garden now.",
    },
  ],

  // Room 7 – Translate from Romanian to English
  7: [
    {
      id: "pc-r7-ex1",
      prompt: "Eu învăț pentru test acum.",
      correct: "i am studying for the test now",
      tts: "I am studying for the test now.",
    },
    {
      id: "pc-r7-ex2",
      prompt: "Ea vorbește la telefon în acest moment.",
      correct: "she is talking on the phone at the moment",
      tts: "She is talking on the phone at the moment.",
    },
    {
      id: "pc-r7-ex3",
      prompt: "Ei se joacă fotbal în parc.",
      correct: "they are playing football in the park",
      tts: "They are playing football in the park.",
    },
    {
      id: "pc-r7-ex4",
      prompt: "Noi ne uităm la un film chiar acum.",
      correct: "we are watching a film right now",
      tts: "We are watching a film right now.",
    },
    {
      id: "pc-r7-ex5",
      prompt: "Mama gătește cina în bucătărie.",
      correct: "mum is cooking dinner in the kitchen",
      tts: "Mum is cooking dinner in the kitchen.",
    },
    {
      id: "pc-r7-ex6",
      prompt: "Copiii desenează în clasă.",
      correct: "the children are drawing in class",
      tts: "The children are drawing in class.",
    },
    {
      id: "pc-r7-ex7",
      prompt: "Tata conduce la muncă acum.",
      correct: "dad is driving to work now",
      tts: "Dad is driving to work now.",
    },
    {
      id: "pc-r7-ex8",
      prompt: "Tu scrii un e-mail important.",
      correct: "you are writing an important email",
      tts: "You are writing an important email.",
    },
    {
      id: "pc-r7-ex9",
      prompt: "Profesorul explică lecția în acest moment.",
      correct: "the teacher is explaining the lesson at the moment",
      tts: "The teacher is explaining the lesson at the moment.",
    },
    {
      id: "pc-r7-ex10",
      prompt: "Afară plouă astăzi.",
      correct: "it is raining outside today",
      tts: "It is raining outside today.",
    },
  ],
};

export function getPcAffirmativeExercises(roomNumber) {
  return PC_AFFIRMATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [];
}

const PC_AFFIRMATIVE_GLOSSARY_BY_ROOM = {
  1: [{ tts: "swimming", word: "swimming", meaning: "a înota" }],
  2: PC_AFFIRMATIVE_ROOM_2_GLOSSARY_ITEMS,
  3: [{ tts: "park", word: "park", meaning: "parc" }],
  4: [{ tts: "eating", word: "eating", meaning: "a mânca (în desfășurare)" }],
  5: [{ tts: "correct", word: "correct", meaning: "corect" }],
  6: [{ tts: "order", word: "order", meaning: "ordine" }],
  7: [{ tts: "today", word: "today", meaning: "astăzi" }],
};

export function getPcAffirmativeGlossaryItems(roomNumber) {
  return PC_AFFIRMATIVE_GLOSSARY_BY_ROOM[roomNumber] ?? [];
}

const PC_AFFIRMATIVE_SECTION_ID = "affirmative";
const PC_AFFIRMATIVE_SECTION_LABEL =
  PC_SECTIONS.find((s) => s.id === PC_AFFIRMATIVE_SECTION_ID)?.title ??
  "Affirmative";

export const PC_AFFIRMATIVE_ROOMS = Array.from(
  { length: PC_ROOMS_PER_SECTION },
  (_, idx) => {
    const roomNumber = idx + 1;
    return {
      sectionId: PC_AFFIRMATIVE_SECTION_ID,
      sectionLabel: PC_AFFIRMATIVE_SECTION_LABEL,
      roomNumber,
      exercises: PC_AFFIRMATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [],
    };
  },
);
