// Present Continuous > Affirmative exercises registry
// Auto-generated by tooling: centralizes exercises per room.
import { PC_ROOMS_PER_SECTION, PC_SECTIONS } from "../pc-core/config.js";


const PC_AFFIRMATIVE_ROOM_2_GLOSSARY_ITEMS = [
  { tts: "like", word: "like", meaning: "a plăcea" },
  { tts: "go", word: "go", meaning: "a merge" },
  { tts: "read", word: "read", meaning: "a citi" },
  { tts: "stop", word: "stop", meaning: "a opri" },
  { tts: "watch", word: "watch", meaning: "a se uita / a privi" },
  { tts: "want", word: "want", meaning: "a vrea" },
  { tts: "wear", word: "wear", meaning: "a purta" },
  { tts: "pupils", word: "pupils", meaning: "elevi" },
  { tts: "traffic lights", word: "traffic lights", meaning: "semafor" },
  { tts: "blouse", word: "blouse", meaning: "bluză" },
];

export const PC_AFFIRMATIVE_EXERCISES_BY_ROOM = {
//
// Optional mini-dictionaries per room (aligned with Present Simple style).
//


  // Room 1 – Verb -> -ing forms (20 verbs)
  1: [
    { id: "pc-r1-ex1", prompt: "run →", correct: "running" },
    { id: "pc-r1-ex2", prompt: "swim →", correct: "swimming" },
    { id: "pc-r1-ex3", prompt: "stop →", correct: "stopping" },
    { id: "pc-r1-ex4", prompt: "plan →", correct: "planning" },
    { id: "pc-r1-ex5", prompt: "shop →", correct: "shopping" },
    { id: "pc-r1-ex6", prompt: "get →", correct: "getting" },
    { id: "pc-r1-ex7", prompt: "sit →", correct: "sitting" },
    { id: "pc-r1-ex8", prompt: "begin →", correct: "beginning" },
    { id: "pc-r1-ex9", prompt: "travel →", correct: "travelling" },
    { id: "pc-r1-ex10", prompt: "study →", correct: "studying" },
    { id: "pc-r1-ex11", prompt: "make →", correct: "making" },
    { id: "pc-r1-ex12", prompt: "take →", correct: "taking" },
    { id: "pc-r1-ex13", prompt: "write →", correct: "writing" },
    { id: "pc-r1-ex14", prompt: "drive →", correct: "driving" },
    { id: "pc-r1-ex15", prompt: "come →", correct: "coming" },
    { id: "pc-r1-ex16", prompt: "dance →", correct: "dancing" },
    { id: "pc-r1-ex17", prompt: "read →", correct: "reading" },
    { id: "pc-r1-ex18", prompt: "play →", correct: "playing" },
    { id: "pc-r1-ex19", prompt: "talk →", correct: "talking" },
    { id: "pc-r1-ex20", prompt: "open →", correct: "opening" },
  ],

  // Room 2 – Completează cu forma corectă a lui "to be"
  2: [
    {
      id: "pc-r2-ex1",
      prompt: "I ____ doing my homework now.",
      correct: "am",
    },
    {
      id: "pc-r2-ex2",
      prompt: "She ____ talking on the phone at the moment.",
      correct: "is",
    },
    {
      id: "pc-r2-ex3",
      prompt: "They ____ playing football in the park.",
      correct: "are",
    },
    {
      id: "pc-r2-ex4",
      prompt: "We ____ watching a film right now.",
      correct: "are",
    },
    {
      id: "pc-r2-ex5",
      prompt: "He ____ listening to music in his room.",
      correct: "is",
    },
    {
      id: "pc-r2-ex6",
      prompt: "You ____ reading a very interesting book.",
      correct: "are",
    },
    {
      id: "pc-r2-ex7",
      prompt: "My sister ____ cooking dinner in the kitchen.",
      correct: "is",
    },
    {
      id: "pc-r2-ex8",
      prompt: "The children ____ drawing pictures in class.",
      correct: "are",
    },
    {
      id: "pc-r2-ex9",
      prompt: "I ____ learning English this week.",
      correct: "am",
    },
    {
      id: "pc-r2-ex10",
      prompt: "My parents ____ working late today.",
      correct: "are",
    },
  ],

  // Room 3 – MCQ (choose the correct option)
  3: [
    {
      id: "pc-r3-ex1",
      prompt: "Look! The dog ___ in the garden.",
      options: [
        { value: "runs", label: "runs" },
        { value: "is-running", label: "is running" },
        { value: "run", label: "run" },
      ],
      correct: "is-running",
    },
    {
      id: "pc-r3-ex2",
      prompt: "They ___ their bikes to school today.",
      options: [
        { value: "are-riding", label: "are riding" },
        { value: "ride", label: "ride" },
        { value: "is-riding", label: "is riding" },
      ],
      correct: "are-riding",
    },
    {
      id: "pc-r3-ex3",
      prompt: "I ___ for my English test now.",
      options: [
        { value: "study", label: "study" },
        { value: "am-studying", label: "am studying" },
        { value: "am-study", label: "am study" },
      ],
      correct: "am-studying",
    },
    {
      id: "pc-r3-ex4",
      prompt: "She ___ her hair at the moment.",
      options: [
        { value: "washes", label: "washes" },
        { value: "is-wash", label: "is wash" },
        { value: "is-washing", label: "is washing" },
      ],
      correct: "is-washing",
    },
    {
      id: "pc-r3-ex5",
      prompt: "We ___ breakfast in the kitchen right now.",
      options: [
        { value: "are-having", label: "are having" },
        { value: "have", label: "have" },
        { value: "is-having", label: "is having" },
      ],
      correct: "are-having",
    },
    {
      id: "pc-r3-ex6",
      prompt: "My brother ___ a new video game.",
      options: [
        { value: "plays", label: "plays" },
        { value: "is-playing", label: "is playing" },
        { value: "are-playing", label: "are playing" },
      ],
      correct: "is-playing",
    },
    {
      id: "pc-r3-ex7",
      prompt: "The teacher ___ to the students.",
      options: [
        { value: "is-talking", label: "is talking" },
        { value: "talks", label: "talks" },
        { value: "are-talking", label: "are talking" },
      ],
      correct: "is-talking",
    },
    {
      id: "pc-r3-ex8",
      prompt: "You ___ too fast!",
      options: [
        { value: "drive", label: "drive" },
        { value: "are-driving", label: "are driving" },
        { value: "is-driving", label: "is driving" },
      ],
      correct: "are-driving",
    },
    {
      id: "pc-r3-ex9",
      prompt: "The boys ___ basketball in the yard.",
      options: [
        { value: "are-playing", label: "are playing" },
        { value: "is-playing", label: "is playing" },
        { value: "play", label: "play" },
      ],
      correct: "are-playing",
    },
    {
      id: "pc-r3-ex10",
      prompt: "It ___ heavily today.",
      options: [
        { value: "is-raining", label: "is raining" },
        { value: "rains", label: "rains" },
        { value: "are-raining", label: "are raining" },
      ],
      correct: "is-raining",
    },
  ],

  // Room 4 – Transformă din Present Simple în Present Continuous
  4: [
    {
      id: "pc-r4-ex1",
      prompt: "Transformă: I eat lunch now.",
      correct: "I am eating lunch now.",
    },
    {
      id: "pc-r4-ex2",
      prompt: "Transformă: She plays the piano at the moment.",
      correct: "She is playing the piano at the moment.",
    },
    {
      id: "pc-r4-ex3",
      prompt: "Transformă: They watch TV right now.",
      correct: "They are watching TV right now.",
    },
    {
      id: "pc-r4-ex4",
      prompt: "Transformă: We read a book together now.",
      correct: "We are reading a book together now.",
    },
    {
      id: "pc-r4-ex5",
      prompt: "Transformă: My brother does his homework at the moment.",
      correct: "My brother is doing his homework at the moment.",
    },
    {
      id: "pc-r4-ex6",
      prompt: "Transformă: The children draw pictures now.",
      correct: "The children are drawing pictures now.",
    },
    {
      id: "pc-r4-ex7",
      prompt: "Transformă: You write an email right now.",
      correct: "You are writing an email right now.",
    },
    {
      id: "pc-r4-ex8",
      prompt: "Transformă: He cleans his room at the moment.",
      correct: "He is cleaning his room at the moment.",
    },
    {
      id: "pc-r4-ex9",
      prompt: "Transformă: My parents cook dinner now.",
      correct: "My parents are cooking dinner now.",
    },
    {
      id: "pc-r4-ex10",
      prompt: "Transformă: The students listen to the teacher right now.",
      correct: "The students are listening to the teacher right now.",
    },
  ],

  // Room 5 – Correct the mistake
  5: [
    {
      id: "pc-r5-ex1",
      prompt: "Corectează: She is play tennis now.",
      correct: "She is playing tennis now.",
    },
    {
      id: "pc-r5-ex2",
      prompt: "Corectează: They are watches a film.",
      correct: "They are watching a film.",
    },
    {
      id: "pc-r5-ex3",
      prompt: "Corectează: I am study for the test.",
      correct: "I am studying for the test.",
    },
    {
      id: "pc-r5-ex4",
      prompt: "Corectează: We is having breakfast at the moment.",
      correct: "We are having breakfast at the moment.",
    },
    {
      id: "pc-r5-ex5",
      prompt: "Corectează: My dad are driving to work now.",
      correct: "My dad is driving to work now.",
    },
    {
      id: "pc-r5-ex6",
      prompt: "Corectează: The children is drawing pictures.",
      correct: "The children are drawing pictures.",
    },
    {
      id: "pc-r5-ex7",
      prompt: "Corectează: You are listen to music too loudly.",
      correct: "You are listening to music too loudly.",
    },
    {
      id: "pc-r5-ex8",
      prompt: "Corectează: Emma am talking to her friend.",
      correct: "Emma is talking to her friend.",
    },
    {
      id: "pc-r5-ex9",
      prompt: "Corectează: It are raining today.",
      correct: "It is raining today.",
    },
    {
      id: "pc-r5-ex10",
      prompt: "Corectează: We are not play football now.",
      correct: "We are not playing football now.",
    },
  ],

  // Room 6 – Put the words in the correct order
  6: [
    {
      id: "pc-r6-ex1",
      prompt: "Pune în ordine: now / is / reading / Anna / a book",
      correct: "Anna is reading a book now.",
    },
    {
      id: "pc-r6-ex2",
      prompt: "Pune în ordine: are / playing / they / in the park / football",
      correct: "They are playing football in the park.",
    },
    {
      id: "pc-r6-ex3",
      prompt: "Pune în ordine: I / for the test / am / studying / today",
      correct: "I am studying for the test today.",
    },
    {
      id: "pc-r6-ex4",
      prompt: "Pune în ordine: is / cooking / my mum / dinner / at the moment",
      correct: "My mum is cooking dinner at the moment.",
    },
    {
      id: "pc-r6-ex5",
      prompt: "Pune în ordine: are / the students / doing / their homework / now",
      correct: "The students are doing their homework now.",
    },
    {
      id: "pc-r6-ex6",
      prompt: "Pune în ordine: listening / we / are / to music / right now",
      correct: "We are listening to music right now.",
    },
    {
      id: "pc-r6-ex7",
      prompt: "Pune în ordine: fixing / is / the car / my uncle / today",
      correct: "My uncle is fixing the car today.",
    },
    {
      id: "pc-r6-ex8",
      prompt: "Pune în ordine: are / the children / watching / a cartoon / now",
      correct: "The children are watching a cartoon now.",
    },
    {
      id: "pc-r6-ex9",
      prompt: "Pune în ordine: writing / is / an email / she / at the moment",
      correct: "She is writing an email at the moment.",
    },
    {
      id: "pc-r6-ex10",
      prompt: "Pune în ordine: running / in the garden / the dog / is / now",
      correct: "The dog is running in the garden now.",
    },
  ],

  // Room 7 – Translate from Romanian to English
  7: [
    {
      id: "pc-r7-ex1",
      prompt: "Tradu: Eu învăț pentru test acum.",
      correct: "I am studying for the test now.",
    },
    {
      id: "pc-r7-ex2",
      prompt: "Tradu: Ea vorbește la telefon în acest moment.",
      correct: "She is talking on the phone at the moment.",
    },
    {
      id: "pc-r7-ex3",
      prompt: "Tradu: Ei se joacă fotbal în parc.",
      correct: "They are playing football in the park.",
    },
    {
      id: "pc-r7-ex4",
      prompt: "Tradu: Noi ne uităm la un film chiar acum.",
      correct: "We are watching a film right now.",
    },
    {
      id: "pc-r7-ex5",
      prompt: "Tradu: Mama gătește cina în bucătărie.",
      correct: "Mum is cooking dinner in the kitchen.",
    },
    {
      id: "pc-r7-ex6",
      prompt: "Tradu: Copiii desenează în clasă.",
      correct: "The children are drawing in class.",
    },
    {
      id: "pc-r7-ex7",
      prompt: "Tradu: Tata conduce la muncă acum.",
      correct: "Dad is driving to work now.",
    },
    {
      id: "pc-r7-ex8",
      prompt: "Tradu: Tu scrii un e-mail important.",
      correct: "You are writing an important email.",
    },
    {
      id: "pc-r7-ex9",
      prompt: "Tradu: Profesorul explică lecția în acest moment.",
      correct: "The teacher is explaining the lesson at the moment.",
    },
    {
      id: "pc-r7-ex10",
      prompt: "Tradu: Afară plouă astăzi.",
      correct: "It is raining outside today.",
    },
  ],
};



export function getPcAffirmativeExercises(roomNumber) {
  return PC_AFFIRMATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [];
}



const PC_AFFIRMATIVE_GLOSSARY_BY_ROOM = {
  1: [
    { tts: "swimming", word: "swimming", meaning: "a înota" },
  ],
  2: PC_AFFIRMATIVE_ROOM_2_GLOSSARY_ITEMS,
  3: [
    { tts: "park", word: "park", meaning: "parc" },
  ],
  4: [
    { tts: "eating", word: "eating", meaning: "a mânca (în desfășurare)" },
  ],
  5: [
    { tts: "correct", word: "correct", meaning: "corect" },
  ],
  6: [
    { tts: "order", word: "order", meaning: "ordine" },
  ],
  7: [
    { tts: "today", word: "today", meaning: "astăzi" },
  ],
};

export function getPcAffirmativeGlossaryItems(roomNumber) {
  return PC_AFFIRMATIVE_GLOSSARY_BY_ROOM[roomNumber] ?? [];
}

const PC_AFFIRMATIVE_SECTION_ID = "affirmative";
const PC_AFFIRMATIVE_SECTION_LABEL =
  PC_SECTIONS.find((s) => s.id === PC_AFFIRMATIVE_SECTION_ID)?.title ?? "Affirmative";

export const PC_AFFIRMATIVE_ROOMS = Array.from({ length: PC_ROOMS_PER_SECTION }, (_, idx) => {
  const roomNumber = idx + 1;
  return {
    sectionId: PC_AFFIRMATIVE_SECTION_ID,
    sectionLabel: PC_AFFIRMATIVE_SECTION_LABEL,
    roomNumber,
    exercises: PC_AFFIRMATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [],
  };
});
