// Present Continuous > Interrogative exercises registry
// Auto-generated by tooling: centralizes exercises per room.
import { PC_ROOMS_PER_SECTION, PC_SECTIONS } from "../pc-core/config.js";

export const PC_INTERROGATIVE_EXERCISES_BY_ROOM = {
  1: [
    {
      id: "pc-r1-ex1",
      template: "[gap] you doing your homework right now?",
      correct: "are",
      tts: "Are you doing your homework right now?",
    },
    {
      id: "pc-r1-ex2",
      template: "[gap] he watching TV at the moment?",
      correct: "is",
      tts: "Is he watching TV at the moment?",
    },
    {
      id: "pc-r1-ex3",
      template: "[gap] she talking on the phone now?",
      correct: "is",
      tts: "Is she talking on the phone now?",
    },
    {
      id: "pc-r1-ex4",
      template: "[gap] they playing football this afternoon?",
      correct: "are",
      tts: "Are they playing football this afternoon?",
    },
    {
      id: "pc-r1-ex5",
      template: "[gap] we having an English lesson today?",
      correct: "are",
      tts: "Are we having an English lesson today?",
    },
    {
      id: "pc-r1-ex6",
      template: "[gap] it raining outside at the moment?",
      correct: "is",
      tts: "Is it raining outside at the moment?",
    },
    {
      id: "pc-r1-ex7",
      template: "[gap] your parents cooking dinner this evening?",
      correct: "are",
      tts: "Are your parents cooking dinner this evening?",
    },
    {
      id: "pc-r1-ex8",
      template: "[gap] your brother studying for the math test now?",
      correct: "is",
      tts: "Is your brother studying for the math test now?",
    },
    {
      id: "pc-r1-ex9",
      template: "[gap] the students working in groups today?",
      correct: "are",
      tts: "Are the students working in groups today?",
    },
    {
      id: "pc-r1-ex10",
      template: "[gap] the teacher explaining the new rule right now?",
      correct: "is",
      tts: "Is the teacher explaining the new rule right now?",
    },
  ],
  2: [
    {
      id: "pc-r2-ex1",
      prompt: "___ I speaking too fast now?",
      correct: "am",
      tts: "Am I speaking too fast now?",
      options: [
        { value: "am", label: "am" },
        { value: "do", label: "do" },
        { value: "are", label: "are" },
      ],
    },
    {
      id: "pc-r2-ex2",
      prompt: "___ you doing your homework right now?",
      correct: "are",
      tts: "Are you doing your homework right now?",
      options: [
        { value: "are", label: "are" },
        { value: "do", label: "do" },
        { value: "is", label: "is" },
      ],
    },
    {
      id: "pc-r2-ex3",
      prompt: "___ she watching TV at the moment?",
      correct: "is",
      tts: "Is she watching TV at the moment?",
      options: [
        { value: "is", label: "is" },
        { value: "does", label: "does" },
        { value: "are", label: "are" },
      ],
    },
    {
      id: "pc-r2-ex4",
      prompt: "___ he talking on the phone now?",
      correct: "is",
      tts: "Is he talking on the phone now?",
      options: [
        { value: "is", label: "is" },
        { value: "does", label: "does" },
        { value: "are", label: "are" },
      ],
    },
    {
      id: "pc-r2-ex5",
      prompt: "___ they playing football this afternoon?",
      correct: "are",
      tts: "Are they playing football this afternoon?",
      options: [
        { value: "are", label: "are" },
        { value: "do", label: "do" },
        { value: "is", label: "is" },
      ],
    },
    {
      id: "pc-r2-ex6",
      prompt: "___ we having an English lesson today?",
      correct: "are",
      tts: "Are we having an English lesson today?",
      options: [
        { value: "are", label: "are" },
        { value: "do", label: "do" },
        { value: "is", label: "is" },
      ],
    },
    {
      id: "pc-r2-ex7",
      prompt: "___ it raining outside now?",
      correct: "is",
      tts: "Is it raining outside now?",
      options: [
        { value: "is", label: "is" },
        { value: "does", label: "does" },
        { value: "are", label: "are" },
      ],
    },
    {
      id: "pc-r2-ex8",
      prompt: "___ your parents cooking dinner this evening?",
      correct: "are",
      tts: "Are your parents cooking dinner this evening?",
      options: [
        { value: "are", label: "are" },
        { value: "do", label: "do" },
        { value: "is", label: "is" },
      ],
    },
    {
      id: "pc-r2-ex9",
      prompt: "___ the children working on a project today?",
      correct: "are",
      tts: "Are the children working on a project today?",
      options: [
        { value: "are", label: "are" },
        { value: "do", label: "do" },
        { value: "is", label: "is" },
      ],
    },
    {
      id: "pc-r2-ex10",
      prompt: "___ the teacher explaining the new exercise right now?",
      correct: "is",
      tts: "Is the teacher explaining the new exercise right now?",
      options: [
        { value: "is", label: "is" },
        { value: "does", label: "does" },
        { value: "are", label: "are" },
      ],
    },
  ],
  3: [
    {
      id: "pc-r3-ex1",
      template: "I am eating lunch now. → [gap]",
      correct: "am i eating lunch now?",
      tts: "Am I eating lunch now?",
    },
    {
      id: "pc-r3-ex2",
      template: "She is doing her homework at the moment. → [gap]",
      correct: "is she doing her homework at the moment?",
      tts: "Is she doing her homework at the moment?",
    },
    {
      id: "pc-r3-ex3",
      template: "They are watching a film tonight. → [gap]",
      correct: "are they watching a film tonight?",
      tts: "Are they watching a film tonight?",
    },
    {
      id: "pc-r3-ex4",
      template: "We are studying for the test this week. → [gap]",
      correct: "are we studying for the test this week?",
      tts: "Are we studying for the test this week?",
    },
    {
      id: "pc-r3-ex5",
      template: "He is talking on the phone now. → [gap]",
      correct: "is he talking on the phone now?",
      tts: "Is he talking on the phone now?",
    },
    {
      id: "pc-r3-ex6",
      template: "The children are playing in the garden right now. → [gap]",
      correct: "are the children playing in the garden right now?",
      tts: "Are the children playing in the garden right now?",
    },
    {
      id: "pc-r3-ex7",
      template: "My mother is cooking dinner today. → [gap]",
      correct: "is my mother cooking dinner today?",
      tts: "Is my mother cooking dinner today?",
    },
    {
      id: "pc-r3-ex8",
      template: "The teacher is explaining a new lesson now. → [gap]",
      correct: "is the teacher explaining a new lesson now?",
      tts: "Is the teacher explaining a new lesson now?",
    },
    {
      id: "pc-r3-ex9",
      template: "Your friends are waiting for you at the bus stop. → [gap]",
      correct: "are your friends waiting for you at the bus stop?",
      tts: "Are your friends waiting for you at the bus stop?",
    },
    {
      id: "pc-r3-ex10",
      template: "The students are working on a project this month. → [gap]",
      correct: "are the students working on a project this month?",
      tts: "Are the students working on a project this month?",
    },
  ],
  4: [
    {
      id: "pc-r4-ex1",
      template:
        "Is she do her homework right now? → [gap] her homework right now?",
      correct: "is she doing",
      tts: "Is she doing her homework right now?",
    },
    {
      id: "pc-r4-ex2",
      template: "Are he watching TV at the moment? →[gap] TV at the moment?",
      correct: "is he watching",
      tts: "Is he watching TV at the moment?",
    },
    {
      id: "pc-r4-ex3",
      template: "Is they playing football now? → [gap] football now?",
      correct: "are they playing",
      tts: "Are they playing football now?",
    },
    {
      id: "pc-r4-ex4",
      template:
        "Am you listening to music right now? → [gap] to music right now?",
      correct: "are you listening",
      tts: "Are you listening to music right now?",
    },
    {
      id: "pc-r4-ex5",
      template: "Are she talking on the phone now? → [gap] on the phone now?",
      correct: "is she talking",
      tts: "Is she talking on the phone now?",
    },
    {
      id: "pc-r4-ex6",
      template:
        "Is we studying for the test today? → [gap] for the test today?",
      correct: "are we studying",
      tts: "Are we studying for the test today?",
    },
    {
      id: "pc-r4-ex7",
      template:
        "Are it raining outside at the moment? → [gap] outside at the moment?",
      correct: "is it raining",
      tts: "Is it raining outside at the moment?",
    },
    {
      id: "pc-r4-ex8",
      template:
        "Is your parents cooking dinner this evening? → [gap] dinner this evening?",
      correct: "are your parents cooking",
      tts: "Are your parents cooking dinner this evening?",
    },
    {
      id: "pc-r4-ex9",
      template:
        "Are the teacher explaining the new rule right now? → [gap] the new rule right now?",
      correct: "is the teacher explaining",
      tts: "Is the teacher explaining the new rule right now?",
    },
    {
      id: "pc-r4-ex10",
      template:
        "Is the children playing in the yard now? → [gap] in the yard now?",
      correct: "are the children playing",
      tts: "Are the children playing in the yard now?",
    },
  ],
  5: [
    {
      id: "pc-r5-ex1",
      template:
        "She is't doing her homework right now. → She [gap] her homework right now.",
      correct: "isn't doing",
      tts: "She isn't doing her homework right now.",
    },
    {
      id: "pc-r5-ex2",
      template:
        "They not playing football in the park today. → They [gap] football in the park today.",
      correct: "aren't playing",
      tts: "They aren't playing football in the park today.",
    },
    {
      id: "pc-r5-ex3",
      template:
        "We aren't study for the test at the moment. → We [gap] for the test at the moment.",
      correct: "aren't studying",
      tts: "We aren't studying for the test at the moment.",
    },
    {
      id: "pc-r5-ex4",
      template: "He isn't listening music now. → He [gap] to music now.",
      correct: "isn't listening",
      tts: "He isn't listening to music now.",
    },
    {
      id: "pc-r5-ex5",
      template: "I amn't watching TV this evening. → I [gap] TV this evening.",
      correct: "am not watching",
      tts: "I am not watching TV this evening.",
    },
    {
      id: "pc-r5-ex6",
      template:
        "The students doesn't working on the project. → The students [gap] on the project.",
      correct: "aren't working",
      tts: "The students aren't working on the project.",
    },
    {
      id: "pc-r5-ex7",
      template:
        "My parents aren't cook dinner at the moment. → My parents [gap] dinner at the moment.",
      correct: "aren't cooking",
      tts: "My parents aren't cooking dinner at the moment.",
    },
    {
      id: "pc-r5-ex8",
      template:
        "You isn't wearing your school uniform today. → You [gap] your school uniform today.",
      correct: "aren't wearing",
      tts: "You aren't wearing your school uniform today.",
    },
    {
      id: "pc-r5-ex9",
      template:
        "The dog aren't sleeping in its bed now. → The dog [gap] in its bed now.",
      correct: "isn't sleeping",
      tts: "The dog isn't sleeping in its bed now.",
    },
    {
      id: "pc-r5-ex10",
      template: "It isn't rain today. → It [gap] today.",
      correct: "isn't raining",
      tts: "It isn't raining today.",
    },
  ],
  6: [
    {
      id: "pc-r6-ex1",
      prompt: "(now / your / doing / are / homework / you)",
      correct: "are you doing your homework now",
      tts: "Are you doing your homework now.",
    },
    {
      id: "pc-r6-ex2",
      prompt: "(moment / tv / at / watching / he / the / is)",
      correct: "is he watching tv at the moment",
      tts: "Is he watching TV at the moment.",
    },
    {
      id: "pc-r6-ex3",
      prompt: "(right / music / to / now / she / is / listening)",
      correct: "is she listening to music right now",
      tts: "Is she listening to music right now.",
    },
    {
      id: "pc-r6-ex4",
      prompt: "(afternoon / football / they / playing / are / this)",
      correct: "are they playing football this afternoon",
      tts: "Are they playing football this afternoon.",
    },
    {
      id: "pc-r6-ex5",
      prompt: "(for / today / test / studying / are / we / the)",
      correct: "are we studying for the test today",
      tts: "Are we studying for the test today.",
    },
    {
      id: "pc-r6-ex6",
      prompt: "(outside / now / raining / it / is)",
      correct: "is it raining outside now",
      tts: "Is it raining outside now.",
    },
    {
      id: "pc-r6-ex7",
      prompt: "(this / dinner / parents / evening / are / your / cooking)",
      correct: "are your parents cooking dinner this evening",
      tts: "Are your parents cooking dinner this evening.",
    },
    {
      id: "pc-r6-ex8",
      prompt: "(studying / now / brother / is / your / right)",
      correct: "is your brother studying right now",
      tts: "Is your brother studying right now.",
    },
    {
      id: "pc-r6-ex9",
      prompt: "(yard / the / now / are / playing / in / children / the)",
      correct: "are the children playing in the yard now",
      tts: "Are the children playing in the yard now.",
    },
    {
      id: "pc-r6-ex10",
      prompt: "(explaining / rule / now / is / the / teacher / new / the)",
      correct: "is the teacher explaining the new rule now",
      tts: "Is the teacher explaining the new rule now.",
    },
  ],
  7: [
    {
      id: "pc-r7-ex1",
      prompt: "Scrii un e-mail acum?",
      correct: "are you writing an email now",
      tts: "Are you writing an email now?",
    },
    {
      id: "pc-r7-ex2",
      prompt: "Se uită ea la televizor în acest moment?",
      correct: "is she watching tv at the moment",
      tts: "Is she watching TV at the moment?",
    },
    {
      id: "pc-r7-ex3",
      prompt: "Învață ei pentru test în seara asta?",
      correct: "are they studying for the test tonight",
      tts: "Are they studying for the test tonight?",
    },
    {
      id: "pc-r7-ex4",
      prompt: "Jucăm noi baschet astăzi?",
      correct: "are we playing basketball today",
      tts: "Are we playing basketball today?",
    },
    {
      id: "pc-r7-ex5",
      prompt: "Vorbește el cu profesorul acum?",
      correct: "is he talking to the teacher now",
      tts: "Is he talking to the teacher now?",
    },
    {
      id: "pc-r7-ex6",
      prompt: "Asculți tu muzică la ora asta?",
      correct: "are you listening to music at this time",
      tts: "Are you listening to music at this time?",
    },
    {
      id: "pc-r7-ex7",
      prompt: "Aleargă copiii în curte acum?",
      correct: "are the children running in the yard now",
      tts: "Are the children running in the yard now?",
    },
    {
      id: "pc-r7-ex8",
      prompt: "Gătesc părinții mei cina în acest moment?",
      correct: "are my parents cooking dinner at the moment",
      tts: "Are my parents cooking dinner at the moment?",
    },
    {
      id: "pc-r7-ex9",
      prompt: "Explică profesorul o nouă lecție acum?",
      correct: "is the teacher explaining a new lesson now",
      tts: "Is the teacher explaining a new lesson now?",
    },
    {
      id: "pc-r7-ex10",
      prompt: "Plouă afară acum?",
      correct: "is it raining outside now",
      tts: "Is it raining outside now?",
    },
  ],
};

export function getPcInterrogativeExercises(roomNumber) {
  return PC_INTERROGATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [];
}

const PC_INTERROGATIVE_GLOSSARY_BY_ROOM = {
  1: [{ tts: "question", word: "question", meaning: "întrebare" }],
  2: [{ tts: "who", word: "who", meaning: "cine" }],
  3: [{ tts: "what", word: "what", meaning: "ce" }],
  4: [{ tts: "where", word: "where", meaning: "unde" }],
  5: [{ tts: "when", word: "when", meaning: "când" }],
  6: [{ tts: "why", word: "why", meaning: "de ce" }],
  7: [{ tts: "how", word: "how", meaning: "cum" }],
};

export function getPcInterrogativeGlossaryItems(roomNumber) {
  return PC_INTERROGATIVE_GLOSSARY_BY_ROOM[roomNumber] ?? [];
}

const PC_INTERROGATIVE_SECTION_ID = "interrogative";
const PC_INTERROGATIVE_SECTION_LABEL =
  PC_SECTIONS.find((s) => s.id === PC_INTERROGATIVE_SECTION_ID)?.title ??
  "Interrogative";

export const PC_INTERROGATIVE_ROOMS = Array.from(
  { length: PC_ROOMS_PER_SECTION },
  (_, idx) => {
    const roomNumber = idx + 1;
    return {
      sectionId: PC_INTERROGATIVE_SECTION_ID,
      sectionLabel: PC_INTERROGATIVE_SECTION_LABEL,
      roomNumber,
      exercises: PC_INTERROGATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [],
    };
  },
);
