// Present Continuous > Interrogative exercises registry
// Auto-generated by tooling: centralizes exercises per room.
import { PC_ROOMS_PER_SECTION, PC_SECTIONS } from "../pc-core/config.js";

export const PC_INTERROGATIVE_EXERCISES_BY_ROOM = {
  1: [
    {
      id: "pc-r1-ex1",
      template: "I [gap] doing my homework right now.",
      correct: "am not",
      tts: "I am not doing my homework right now.",
    },
    {
      id: "pc-r1-ex2",
      template: "She [gap] watching TV at the moment.",
      correct: "is not",
      tts: "She is not watching TV at the moment.",
    },
    {
      id: "pc-r1-ex3",
      template: "They [gap] playing football in the park today.",
      correct: "are not",
      tts: "They are not playing football in the park today.",
    },
    {
      id: "pc-r1-ex4",
      template: "We [gap] studying for the test this evening.",
      correct: "are not",
      tts: "We are not studying for the test this evening.",
    },
    {
      id: "pc-r1-ex5",
      template: "He [gap] listening to music in his room.",
      correct: "is not",
      tts: "He is not listening to music in his room.",
    },
    {
      id: "pc-r1-ex6",
      template: "You [gap] talking to the teacher right now.",
      correct: "are not",
      tts: "You are not talking to the teacher right now.",
    },
    {
      id: "pc-r1-ex7",
      template: "The dog [gap] sleeping under the table.",
      correct: "is not",
      tts: "The dog is not sleeping under the table.",
    },
    {
      id: "pc-r1-ex8",
      template: "My parents [gap] cooking dinner at the moment.",
      correct: "are not",
      tts: "My parents are not cooking dinner at the moment.",
    },
    {
      id: "pc-r1-ex9",
      template: "The students [gap] working on their projects now.",
      correct: "are not",
      tts: "The students are not working on their projects now.",
    },
    {
      id: "pc-r1-ex10",
      template: "It [gap] raining today, so we can go outside.",
      correct: "is not",
      tts: "It is not raining today, so we can go outside.",
    },
  ],
  2: [
    {
      id: "pc-r2-ex1",
      template: "I [gap] doing the dishes right now.",
      correct: "'m not",
      tts: "I'm not doing the dishes right now.",
    },
    {
      id: "pc-r2-ex2",
      template: "She [gap] reading that book at the moment.",
      correct: "isn't",
      tts: "She isn't reading that book at the moment.",
    },
    {
      id: "pc-r2-ex3",
      template: "They [gap] waiting for the bus now.",
      correct: "aren't",
      tts: "They aren't waiting for the bus now.",
    },
    {
      id: "pc-r2-ex4",
      template: "We [gap] playing computer games this evening.",
      correct: "aren't",
      tts: "We aren't playing computer games this evening.",
    },
    {
      id: "pc-r2-ex5",
      template: "He [gap] talking on the phone right now.",
      correct: "isn't",
      tts: "He isn't talking on the phone right now.",
    },
    {
      id: "pc-r2-ex6",
      template: "You [gap] wearing your school uniform today.",
      correct: "aren't",
      tts: "You aren't wearing your school uniform today.",
    },
    {
      id: "pc-r2-ex7",
      template: "The children [gap] drawing in their notebooks.",
      correct: "aren't",
      tts: "The children aren't drawing in their notebooks.",
    },
    {
      id: "pc-r2-ex8",
      template: "My brother and I [gap] studying in the library now.",
      correct: "aren't",
      tts: "My brother and I aren't studying in the library now.",
    },
    {
      id: "pc-r2-ex9",
      template: "The teacher [gap] explaining a new rule at the moment.",
      correct: "isn't",
      tts: "The teacher isn't explaining a new rule at the moment.",
    },
    {
      id: "pc-r2-ex10",
      template: "It [gap] getting dark yet.",
      correct: "isn't",
      tts: "It isn't getting dark yet.",
    },
  ],
  3: [
    {
      id: "pc-r3-ex1",
      prompt: "She ___ to music right now.",
      correct: "is-not-listening",
      tts: "She is not listening to music right now.",
      options: [
        { value: "doesnt-listen", label: "doesn't listen" },
        { value: "is-not-listening", label: "is not listening" },
        { value: "not-listening", label: "not listening" },
      ],
    },
    {
      id: "pc-r3-ex2",
      prompt: "They ___ for the exam this evening.",
      correct: "are-not-studying",
      tts: "They are not studying for the exam this evening.",
      options: [
        { value: "arent-study", label: "aren't study" },
        { value: "are-not-studying", label: "are not studying" },
        { value: "dont-studying", label: "don't studying" },
      ],
    },
    {
      id: "pc-r3-ex3",
      prompt: "I ___ my lunch at the moment.",
      correct: "am-not-eating",
      tts: "I am not eating my lunch at the moment.",
      options: [
        { value: "am-not-eating", label: "am not eating" },
        { value: "am-not-eat", label: "am not eat" },
        { value: "dont-eating", label: "don't eating" },
      ],
    },
    {
      id: "pc-r3-ex4",
      prompt: "We ___ basketball today.",
      correct: "are-not-playing",
      tts: "We are not playing basketball today.",
      options: [
        { value: "are-not-playing", label: "are not playing" },
        { value: "dont-playing", label: "don't playing" },
        { value: "arent-play", label: "aren't play" },
      ],
    },
    {
      id: "pc-r3-ex5",
      prompt: "He ___ to school this week; he's sick.",
      correct: "is-not-going",
      tts: "He is not going to school this week; he's sick.",
      options: [
        { value: "is-not-going", label: "is not going" },
        { value: "isnt-go", label: "isn't go" },
        { value: "dont-going", label: "don't going" },
      ],
    },
    {
      id: "pc-r3-ex6",
      prompt: "The students ___ to the teacher right now.",
      correct: "are-not-listening",
      tts: "The students are not listening to the teacher right now.",
      options: [
        { value: "are-not-listening", label: "are not listening" },
        { value: "dont-listen-now", label: "don't listen now" },
        { value: "arent-listen", label: "aren't listen" },
      ],
    },
    {
      id: "pc-r3-ex7",
      prompt: "My parents ___ dinner at the moment.",
      correct: "are-not-cooking",
      tts: "My parents are not cooking dinner at the moment.",
      options: [
        { value: "dont-cooking", label: "don't cooking" },
        { value: "are-not-cooking", label: "are not cooking" },
        { value: "arent-cook", label: "aren't cook" },
      ],
    },
    {
      id: "pc-r3-ex8",
      prompt: "It ___ outside now.",
      correct: "is-not-raining",
      tts: "It is not raining outside now.",
      options: [
        { value: "isnt-rain", label: "isn't rain" },
        { value: "is-not-raining", label: "is not raining" },
        { value: "not-raining", label: "not raining" },
      ],
    },
    {
      id: "pc-r3-ex9",
      prompt: "You ___ the test right now.",
      correct: "are-not-writing",
      tts: "You are not writing the test right now.",
      options: [
        { value: "arent-write", label: "aren't write" },
        { value: "dont-writing", label: "don't writing" },
        { value: "are-not-writing", label: "are not writing" },
      ],
    },
    {
      id: "pc-r3-ex10",
      prompt: "The kids ___ in the garden today.",
      correct: "are-not-playing",
      tts: "The kids are not playing in the garden today.",
      options: [
        { value: "arent-play", label: "aren't play" },
        { value: "dont-playing", label: "don't playing" },
        { value: "are-not-playing", label: "are not playing" },
      ],
    },
  ],
  4: [
    {
      id: "pc-r4-ex1",
      template: "I am eating lunch now. → I [gap] lunch now.",
      correct: "am not eating",
      tts: "I'm not eating lunch now.",
    },
    {
      id: "pc-r4-ex2",
      template:
        "She is doing her homework right now. → She [gap] her homework right now.",
      correct: "is not doing",
      tts: "She is not doing her homework right now.",
    },
    {
      id: "pc-r4-ex3",
      template:
        "They are playing football in the park today. → They [gap] football in the park today.",
      correct: "are not playing",
      tts: "They are not playing football in the park today.",
    },
    {
      id: "pc-r4-ex4",
      template:
        "We are studying for the English test today. → We [gap] for the English test today.",
      correct: "are not studying",
      tts: "We are not studying for the English test today.",
    },
    {
      id: "pc-r4-ex5",
      template:
        "He is talking to his best friend at the moment. → He [gap] to his best friend at the moment.",
      correct: "is not talking",
      tts: "He is not talking to his best friend at the moment.",
    },
    {
      id: "pc-r4-ex6",
      template:
        "The kids are running in the corridor. → The kids [gap] in the corridor.",
      correct: "are not running",
      tts: "The kids are not running in the corridor.",
    },
    {
      id: "pc-r4-ex7",
      template:
        "My parents are cooking pasta for dinner. → My parents [gap] pasta for dinner.",
      correct: "are not cooking",
      tts: "My parents are not cooking pasta for dinner.",
    },
    {
      id: "pc-r4-ex8",
      template:
        "You are using my laptop at the moment. → You [gap] my laptop at the moment.",
      correct: "are not using",
      tts: "You are not using my laptop at the moment.",
    },
    {
      id: "pc-r4-ex9",
      template:
        "The teacher is checking our exercises right now. → The teacher [gap] our exercises right now.",
      correct: "is not checking",
      tts: "The teacher is not checking our exercises right now.",
    },
    {
      id: "pc-r4-ex10",
      template: "It is snowing outside today. → It [gap] outside today.",
      correct: "is not snowing",
      tts: "It is not snowing outside today.",
    },
  ],
  5: [
    {
      id: "pc-r5-ex1",
      template:
        "She is't doing her homework right now. → She [gap] her homework right now.",
      correct: "isn't doing",
      tts: "She isn't doing her homework right now.",
    },
    {
      id: "pc-r5-ex2",
      template:
        "They not playing football in the park today. → They [gap] football in the park today.",
      correct: "aren't playing",
      tts: "They aren't playing football in the park today.",
    },
    {
      id: "pc-r5-ex3",
      template:
        "We aren't study for the test at the moment. → We [gap] for the test at the moment.",
      correct: "aren't studying",
      tts: "We aren't studying for the test at the moment.",
    },
    {
      id: "pc-r5-ex4",
      template: "He isn't listening music now. → He [gap] to music now.",
      correct: "isn't listening",
      tts: "He isn't listening to music now.",
    },
    {
      id: "pc-r5-ex5",
      template: "I amn't watching TV this evening. → I [gap] TV this evening.",
      correct: "am not watching",
      tts: "I am not watching TV this evening.",
    },
    {
      id: "pc-r5-ex6",
      template:
        "The students doesn't working on the project. → The students [gap] on the project.",
      correct: "aren't working",
      tts: "The students aren't working on the project.",
    },
    {
      id: "pc-r5-ex7",
      template:
        "My parents aren't cook dinner at the moment. → My parents [gap] dinner at the moment.",
      correct: "aren't cooking",
      tts: "My parents aren't cooking dinner at the moment.",
    },
    {
      id: "pc-r5-ex8",
      template:
        "You isn't wearing your school uniform today. → You [gap] your school uniform today.",
      correct: "aren't wearing",
      tts: "You aren't wearing your school uniform today.",
    },
    {
      id: "pc-r5-ex9",
      template:
        "The dog aren't sleeping in its bed now. → The dog [gap] in its bed now.",
      correct: "isn't sleeping",
      tts: "The dog isn't sleeping in its bed now.",
    },
    {
      id: "pc-r5-ex10",
      template: "It isn't rain today. → It [gap] today.",
      correct: "isn't raining",
      tts: "It isn't raining today.",
    },
  ],
  6: [
    {
      id: "pc-r6-ex1",
      prompt: "(doing / I / my / am / not / homework / now)",
      correct: "i am not doing my homework now",
      tts: "I am not doing my homework now.",
    },
    {
      id: "pc-r6-ex2",
      prompt: "(is / watching / she / TV / not / at the moment)",
      correct: "she is not watching tv at the moment",
      tts: "She is not watching TV at the moment.",
    },
    {
      id: "pc-r6-ex3",
      prompt: "(playing / are / not / they / football / today)",
      correct: "they are not playing football today",
      tts: "They are not playing football today.",
    },
    {
      id: "pc-r6-ex4",
      prompt: "(we / for / are / not / studying / the test / now)",
      correct: "we are not studying for the test now",
      tts: "We are not studying for the test now.",
    },
    {
      id: "pc-r6-ex5",
      prompt: "(listening / he / not / is / to music / right now)",
      correct: "he is not listening to music right now",
      tts: "He is not listening to music right now.",
    },
    {
      id: "pc-r6-ex6",
      prompt: "(using / are / not / you / my / phone / at the moment)",
      correct: "you are not using my phone at the moment",
      tts: "You are not using my phone at the moment.",
    },
    {
      id: "pc-r6-ex7",
      prompt: "(the / are / not / children / in the garden / playing)",
      correct: "the children are not playing in the garden",
      tts: "The children are not playing in the garden.",
    },
    {
      id: "pc-r6-ex8",
      prompt: "(working / parents / my / are / not / late / tonight)",
      correct: "my parents are not working late tonight",
      tts: "My parents are not working late tonight.",
    },
    {
      id: "pc-r6-ex9",
      prompt: "(it / not / raining / is / outside / now)",
      correct: "it is not raining outside now",
      tts: "It is not raining outside now.",
    },
    {
      id: "pc-r6-ex10",
      prompt: "(students / the / are / not / talking / in class / now)",
      correct: "the students are not talking in class now",
      tts: "The students are not talking in class now.",
    },
  ],
  7: [
    {
      id: "pc-r7-ex1",
      prompt: "Eu nu scriu un e-mail acum.",
      correct: "i am not writing an email now",
      tts: "I am not writing an email now.",
    },
    {
      id: "pc-r7-ex2",
      prompt: "Ea nu se uită la televizor în acest moment.",
      correct: "she is not watching tv at the moment",
      tts: "She is not watching TV at the moment.",
    },
    {
      id: "pc-r7-ex3",
      prompt: "Ei nu învață pentru test în seara asta.",
      correct: "they are not studying for the test tonight",
      tts: "They are not studying for the test tonight.",
    },
    {
      id: "pc-r7-ex4",
      prompt: "Noi nu jucăm baschet astăzi.",
      correct: "we are not playing basketball today",
      tts: "We are not playing basketball today.",
    },
    {
      id: "pc-r7-ex5",
      prompt: "El nu vorbește cu profesorul acum.",
      correct: "he is not talking to the teacher now",
      tts: "He is not talking to the teacher now.",
    },
    {
      id: "pc-r7-ex6",
      prompt: "Tu nu asculți muzică la ora asta.",
      correct: "you are not listening to music right now",
      tts: "You are not listening to music right now.",
    },
    {
      id: "pc-r7-ex7",
      prompt: "Copiii nu aleargă în curte acum.",
      correct: "the children are not running in the yard now",
      tts: "The children are not running in the yard now.",
    },
    {
      id: "pc-r7-ex8",
      prompt: "Părinții mei nu gătesc cina în acest moment.",
      correct: "my parents are not cooking dinner at the moment",
      tts: "My parents are not cooking dinner at the moment.",
    },
    {
      id: "pc-r7-ex9",
      prompt: "Profesorul nu explică o nouă lecție acum.",
      correct: "the teacher is not explaining a new lesson now",
      tts: "The teacher is not explaining a new lesson now.",
    },
    {
      id: "pc-r7-ex10",
      prompt: "Afară nu plouă acum.",
      correct: "it is not raining now",
      tts: "It is not raining now.",
    },
  ],
};

export function getPcInterrogativeExercises(roomNumber) {
  return PC_INTERROGATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [];
}

const PC_INTERROGATIVE_GLOSSARY_BY_ROOM = {
  1: [{ tts: "question", word: "question", meaning: "întrebare" }],
  2: [{ tts: "who", word: "who", meaning: "cine" }],
  3: [{ tts: "what", word: "what", meaning: "ce" }],
  4: [{ tts: "where", word: "where", meaning: "unde" }],
  5: [{ tts: "when", word: "when", meaning: "când" }],
  6: [{ tts: "why", word: "why", meaning: "de ce" }],
  7: [{ tts: "how", word: "how", meaning: "cum" }],
};

export function getPcInterrogativeGlossaryItems(roomNumber) {
  return PC_INTERROGATIVE_GLOSSARY_BY_ROOM[roomNumber] ?? [];
}

const PC_INTERROGATIVE_SECTION_ID = "interrogative";
const PC_INTERROGATIVE_SECTION_LABEL =
  PC_SECTIONS.find((s) => s.id === PC_INTERROGATIVE_SECTION_ID)?.title ??
  "Interrogative";

export const PC_INTERROGATIVE_ROOMS = Array.from(
  { length: PC_ROOMS_PER_SECTION },
  (_, idx) => {
    const roomNumber = idx + 1;
    return {
      sectionId: PC_INTERROGATIVE_SECTION_ID,
      sectionLabel: PC_INTERROGATIVE_SECTION_LABEL,
      roomNumber,
      exercises: PC_INTERROGATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [],
    };
  },
);
