// Present Continuous > Interrogative exercises registry
// Auto-generated by tooling: centralizes exercises per room.
import { PC_ROOMS_PER_SECTION, PC_SECTIONS } from "../pc-core/config.js";


export const PC_INTERROGATIVE_EXERCISES_BY_ROOM = {
  1: [
      {
        id: "pc-interrogative-r1-ex1",
        prompt: "Scrie forma interogativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  2: [
      {
        id: "pc-interrogative-r2-ex1",
        prompt: "Scrie forma interogativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  3: [
      {
        id: "pc-interrogative-r3-ex1",
        prompt: "Scrie forma interogativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  4: [
      {
        id: "pc-interrogative-r4-ex1",
        prompt: "Scrie forma interogativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  5: [
      {
        id: "pc-interrogative-r5-ex1",
        prompt: "Scrie forma interogativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  6: [
      {
        id: "pc-interrogative-r6-ex1",
        prompt: "Scrie forma interogativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  7: [
      {
        id: "pc-interrogative-r7-ex1",
        prompt: "Scrie forma interogativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
};

export function getPcInterrogativeExercises(roomNumber) {
  return PC_INTERROGATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [];
}

const PC_INTERROGATIVE_GLOSSARY_BY_ROOM = {
  1: [{ tts: "question", word: "question", meaning: "întrebare" }],
  2: [{ tts: "who", word: "who", meaning: "cine" }],
  3: [{ tts: "what", word: "what", meaning: "ce" }],
  4: [{ tts: "where", word: "where", meaning: "unde" }],
  5: [{ tts: "when", word: "when", meaning: "când" }],
  6: [{ tts: "why", word: "why", meaning: "de ce" }],
  7: [{ tts: "how", word: "how", meaning: "cum" }],
};

export function getPcInterrogativeGlossaryItems(roomNumber) {
  return PC_INTERROGATIVE_GLOSSARY_BY_ROOM[roomNumber] ?? [];
}

const PC_INTERROGATIVE_SECTION_ID = "interrogative";
const PC_INTERROGATIVE_SECTION_LABEL =
  PC_SECTIONS.find((s) => s.id === PC_INTERROGATIVE_SECTION_ID)?.title ?? "Interrogative";

export const PC_INTERROGATIVE_ROOMS = Array.from({ length: PC_ROOMS_PER_SECTION }, (_, idx) => {
  const roomNumber = idx + 1;
  return {
    sectionId: PC_INTERROGATIVE_SECTION_ID,
    sectionLabel: PC_INTERROGATIVE_SECTION_LABEL,
    roomNumber,
    exercises: PC_INTERROGATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [],
  };
});
