// Present Continuous > Negative exercises registry
// Auto-generated by tooling: centralizes exercises per room.
import { PC_ROOMS_PER_SECTION, PC_SECTIONS } from "../pc-core/config.js";


export const PC_NEGATIVE_EXERCISES_BY_ROOM = {
  1: [
      {
        id: "pc-negative-r1-ex1",
        prompt: "Scrie forma negativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  2: [
      {
        id: "pc-negative-r2-ex1",
        prompt: "Scrie forma negativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  3: [
      {
        id: "pc-negative-r3-ex1",
        prompt: "Scrie forma negativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  4: [
      {
        id: "pc-negative-r4-ex1",
        prompt: "Scrie forma negativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  5: [
      {
        id: "pc-negative-r5-ex1",
        prompt: "Scrie forma negativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  6: [
      {
        id: "pc-negative-r6-ex1",
        prompt: "Scrie forma negativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
  7: [
      {
        id: "pc-negative-r7-ex1",
        prompt: "Scrie forma negativă corectă a propoziției date.",
        correct: "todo",
      },
    ],
};

export function getPcNegativeExercises(roomNumber) {
  return PC_NEGATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [];
}

const PC_NEGATIVE_GLOSSARY_BY_ROOM = {
  1: [{ tts: "not", word: "not", meaning: "nu" }],
  2: [{ tts: "never", word: "never", meaning: "niciodată" }],
  3: [{ tts: "nothing", word: "nothing", meaning: "nimic" }],
  4: [{ tts: "nobody", word: "nobody", meaning: "nimeni" }],
  5: [{ tts: "nowhere", word: "nowhere", meaning: "nicăieri" }],
  6: [{ tts: "hardly", word: "hardly", meaning: "aproape deloc" }],
  7: [{ tts: "no", word: "no", meaning: "nu / niciun" }],
};

export function getPcNegativeGlossaryItems(roomNumber) {
  return PC_NEGATIVE_GLOSSARY_BY_ROOM[roomNumber] ?? [];
}

const PC_NEGATIVE_SECTION_ID = "negative";
const PC_NEGATIVE_SECTION_LABEL =
  PC_SECTIONS.find((s) => s.id === PC_NEGATIVE_SECTION_ID)?.title ?? "Negative";

export const PC_NEGATIVE_ROOMS = Array.from({ length: PC_ROOMS_PER_SECTION }, (_, idx) => {
  const roomNumber = idx + 1;
  return {
    sectionId: PC_NEGATIVE_SECTION_ID,
    sectionLabel: PC_NEGATIVE_SECTION_LABEL,
    roomNumber,
    exercises: PC_NEGATIVE_EXERCISES_BY_ROOM[roomNumber] ?? [],
  };
});
