// Present Continuous > Time Expressions exercises registry
// Auto-generated by tooling: centralizes exercises per room.
import { PC_ROOMS_PER_SECTION, PC_SECTIONS } from "../pc-core/config.js";


export const PC_TIMEEXPRESSIONS_EXERCISES_BY_ROOM = {
  1: [
      {
        id: "pc-time-expressions-room1-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  2: [
      {
        id: "pc-time-expressions-room2-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  3: [
      {
        id: "pc-time-expressions-room3-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  4: [
      {
        id: "pc-time-expressions-room4-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  5: [
      {
        id: "pc-time-expressions-room5-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  6: [
      {
        id: "pc-time-expressions-room6-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  7: [
      {
        id: "pc-time-expressions-room7-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
};

export function getPcTimeExpressionsExercises(roomNumber) {
  return PC_TIMEEXPRESSIONS_EXERCISES_BY_ROOM[roomNumber] ?? [];
}

const PC_TIMEEXPRESSIONS_GLOSSARY_BY_ROOM = {
  1: [{ tts: "now", word: "now", meaning: "acum" }],
  2: [{ tts: "at-the-moment", word: "at the moment", meaning: "în acest moment" }],
  3: [{ tts: "today", word: "today", meaning: "astăzi" }],
  4: [{ tts: "this-week", word: "this week", meaning: "săptămâna aceasta" }],
  5: [{ tts: "tonight", word: "tonight", meaning: "în seara asta" }],
  6: [{ tts: "this-morning", word: "this morning", meaning: "în dimineața asta" }],
  7: [{ tts: "these-days", word: "these days", meaning: "zilele astea" }],
};

export function getPcTimeExpressionsGlossaryItems(roomNumber) {
  return PC_TIMEEXPRESSIONS_GLOSSARY_BY_ROOM[roomNumber] ?? [];
}

const PC_TIMEEXPRESSIONS_SECTION_ID = "time-expressions";
const PC_TIMEEXPRESSIONS_SECTION_LABEL =
  PC_SECTIONS.find((s) => s.id === PC_TIMEEXPRESSIONS_SECTION_ID)?.title ?? "Time Expressions";

export const PC_TIMEEXPRESSIONS_ROOMS = Array.from({ length: PC_ROOMS_PER_SECTION }, (_, idx) => {
  const roomNumber = idx + 1;
  return {
    sectionId: PC_TIMEEXPRESSIONS_SECTION_ID,
    sectionLabel: PC_TIMEEXPRESSIONS_SECTION_LABEL,
    roomNumber,
    exercises: PC_TIMEEXPRESSIONS_EXERCISES_BY_ROOM[roomNumber] ?? [],
  };
});
