// Present Continuous > Uses exercises registry
// Auto-generated by tooling: centralizes exercises per room.
import { PC_ROOMS_PER_SECTION, PC_SECTIONS } from "../pc-core/config.js";


export const PC_USES_EXERCISES_BY_ROOM = {
  1: [
      {
        id: "pc-uses-room1-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  2: [
      {
        id: "pc-uses-room2-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  3: [
      {
        id: "pc-uses-room3-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  4: [
      {
        id: "pc-uses-room4-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  5: [
      {
        id: "pc-uses-room5-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  6: [
      {
        id: "pc-uses-room6-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
  7: [
      {
        id: "pc-uses-room7-ex1",
        prompt: "Placeholder – vom adăuga exercițiile reale aici.",
        correct: "todo",
      },
    ],
};

export function getPcUsesExercises(roomNumber) {
  return PC_USES_EXERCISES_BY_ROOM[roomNumber] ?? [];
}

const PC_USES_GLOSSARY_BY_ROOM = {
  1: [{ tts: "always", word: "always", meaning: "întotdeauna" }],
  2: [{ tts: "usually", word: "usually", meaning: "de obicei" }],
  3: [{ tts: "often", word: "often", meaning: "adesea" }],
  4: [{ tts: "sometimes", word: "sometimes", meaning: "uneori" }],
  5: [{ tts: "rarely", word: "rarely", meaning: "rar" }],
  6: [{ tts: "never", word: "never", meaning: "niciodată" }],
  7: [{ tts: "right-now", word: "right now", meaning: "chiar acum" }],
};

export function getPcUsesGlossaryItems(roomNumber) {
  return PC_USES_GLOSSARY_BY_ROOM[roomNumber] ?? [];
}

const PC_USES_SECTION_ID = "uses";
const PC_USES_SECTION_LABEL =
  PC_SECTIONS.find((s) => s.id === PC_USES_SECTION_ID)?.title ?? "Uses";

export const PC_USES_ROOMS = Array.from({ length: PC_ROOMS_PER_SECTION }, (_, idx) => {
  const roomNumber = idx + 1;
  return {
    sectionId: PC_USES_SECTION_ID,
    sectionLabel: PC_USES_SECTION_LABEL,
    roomNumber,
    exercises: PC_USES_EXERCISES_BY_ROOM[roomNumber] ?? [],
  };
});
